version: '3'
services:
    app:
        container_name: sinatra-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '4567:4567'
        volumes:
            - .:/app
        networks:
            - trandung
networks:
    trandung:
