version: '3.9'
services:
    app:
        container_name: django-container
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8000:8000'
        env_file: .env
        volumes:
            - .:/app
        networks:
            - trandung
networks:
    trandung:
