version: '3.8'
services:
    backend:
        container_name: rails-container
        restart: unless-stopped
        build:
            context: .
            dockerfile: Dockerfile
        # command:
        command: bash -c "bundle exec rails server -b '0.0.0.0'"
        ports:
            - '3000:3000'
        volumes:
            - '.:/app'
        networks:
            - trandung
networks:
    trandung:
