version: '3.8'
services:
    app:
        container_name: gin-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes:
            - .:/app
        networks:
            - trandung
networks:
    trandung:
