---
version: '3.7'
services:
    app:
        container_name: gin-container
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - ./:/app
        environment:
            PORT: '8080'
        networks:
            - trandung
networks:
    trandung:
