version: '3.9'
services:
    app:
        image: trandung2001/nodejs:v1
        container_name: nodejs-container
        working_dir: /app
        build:
            context: .
            dockerfile: Dockerfile.dev
        restart: unless-stopped
        expose:
            - 4000
        ports:
            - 4000:4000
        volumes:
            - './src:/app/src'
            - /app/node_modules
        environment:
            PORT: 4000
            MYSQL_USER: root
            MYSQL_PASSWORD: root
            MYSQL_DB: todoDB
    mysql_db:
        image: mysql:latest
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todoDB
        volumes:
            - mysql-database:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql_db
volumes:
    mysql-database:
