version: '3.9'
services:
    php:
        container_name: php-container
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        ports:
            - 4000:80
    mysql_db:
        image: mysql:latest
        container_name: mysql-container
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: mydb
        volumes:
            - mysql-database:/var/lib/mysql
    phpmyadmin:
        image: phpmyadmin:latest
        restart: always
        ports:
            - 8080:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=mysql_db
volumes:
    mysql-database:
